/* print.js — the print kit (docs/features/print-kit.md): cover sheet, letter
   sheet, instructions page, token sheet, register page. Print CSS is the
   engine; each .sheet is page-break-isolated and self-identifying. */
(function (root) {
  'use strict';

  function el(tag, cls, text) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text !== undefined) n.textContent = text;
    return n;
  }

  function footer(id, openLine) {
    var f = el('div', 'sheet-footer');
    f.appendChild(el('span', '', id));
    f.appendChild(el('span', '', openLine));
    return f;
  }

  function coverSheet(s) {
    var M = root.TesseraManifest;
    var f = s.fields;
    var sheet = el('section', 'sheet sheet-cover');
    sheet.appendChild(el('div', 'cover-rule'));
    sheet.appendChild(el('p', 'cover-kicker', 'A letter, sealed ' + M.dateInWords(f.written) + '.'));
    var title = f.openWhenNeeded && s.coverLine ? s.coverLine
      : 'To be opened by ' + f.to + ' on ' + M.dateInWords(f.openOn) + '.';
    sheet.appendChild(el('h2', 'cover-title', title));
    sheet.appendChild(el('p', 'cover-plea', f.openWhenNeeded
      ? 'Not out of curiosity, if you can bear it.'
      : 'Not before, if you can bear it.'));
    var promises = el('div', 'cover-promises');
    promises.appendChild(el('h3', '', 'If you are keeping this for someone'));
    var ul = el('ul', '');
    ['Keep it dry, and keep it with this page.',
      'Don’t open it. It isn’t yours to open.',
      'Never destroy it unread; passing it on is always the alternative.',
      'If you pass it on, pass its story with it.'].forEach(function (t) {
        ul.appendChild(el('li', '', t));
      });
    promises.appendChild(ul);
    sheet.appendChild(promises);
    sheet.appendChild(el('p', 'sheet-note', 'This page goes on the outside. Fold it around the sealed envelope, or paste it to the front.'));
    sheet.appendChild(footer(f.id, f.openWhenNeeded ? 'opens when needed' : 'opens ' + f.openOn));
    return sheet;
  }

  function letterSheet(s) {
    var f = s.fields;
    var sheet = el('section', 'sheet sheet-letter');
    var body = el('div', 'letter-body');
    var paras = s.letterText.split(/\n\n+/);
    for (var i = 0; i < paras.length; i++) {
      if (paras[i].trim().length) body.appendChild(el('p', '', paras[i].trim()));
    }
    sheet.appendChild(body);
    sheet.appendChild(footer(f.id, f.openWhenNeeded ? 'opens when needed' : 'opens ' + f.openOn));
    return sheet;
  }

  function instructionsSheet(s) {
    var f = s.fields;
    var sheet = el('section', 'sheet sheet-instructions');
    var pre = el('pre', 'readme-pre', s.readme);
    sheet.appendChild(pre);
    sheet.appendChild(footer(f.id, 'instructions'));
    return sheet;
  }

  function tokenSheet(s) {
    var f = s.fields;
    var sheet = el('section', 'sheet sheet-token');
    sheet.appendChild(el('h2', 'sheet-heading', 'The token'));
    sheet.appendChild(el('p', 'sheet-note',
      'Print this page on the stiffest paper you have. Cut along the dashed line. ' +
      'One half stays with the writer; the other travels sealed with the letter. ' +
      'Decades from now, the broken edge is the signature: the halves must meet.'));
    var holder = el('div', 'token-holder');
    holder.innerHTML = s.token.sheet; /* generated by token.js from the seed — no user HTML */
    sheet.appendChild(holder);
    sheet.appendChild(footer(f.id, 'token'));
    return sheet;
  }

  function kitSheets(sealed) {
    var occ = root.TesseraOccasions.bySlug(sealed.fields.occasion || 'custom');
    sealed.coverLine = occ.coverLine ? 'To be opened ' + occ.title.replace(/^Open /, '') + '.' : '';
    if (occ.group === 'open-when') sealed.coverLine = occ.title + '.';
    var sheets = [coverSheet(sealed)];
    if (sealed.letterText) sheets.push(letterSheet(sealed));
    sheets.push(instructionsSheet(sealed));
    if (sealed.token) sheets.push(tokenSheet(sealed));
    return sheets;
  }

  function registerSheet(entries) {
    var M = root.TesseraManifest;
    var sheet = el('section', 'sheet sheet-register');
    sheet.appendChild(el('h2', 'sheet-heading', 'Letters in this house, waiting.'));
    var table = el('table', 'register-table');
    var head = el('tr', '');
    ['Letter', 'For', 'Sealed', 'Opens', 'Kept by'].forEach(function (h) { head.appendChild(el('th', '', h)); });
    table.appendChild(head);
    entries.forEach(function (e) {
      var tr = el('tr', '');
      tr.appendChild(el('td', 'mono', e.id));
      tr.appendChild(el('td', '', e.to));
      tr.appendChild(el('td', '', e.written));
      tr.appendChild(el('td', '', e.openWhenNeeded ? 'when needed' : M.dateInWords(e.openOn)));
      tr.appendChild(el('td', '', e.custodyHolder || 'the writer'));
      table.appendChild(tr);
    });
    sheet.appendChild(table);
    sheet.appendChild(el('p', 'sheet-note', 'Keep this page with the family papers, and reprint it when it changes.'));
    return sheet;
  }

  /* the open-dates card: one A4 sheet holding the same card twice, split by a
     dashed cut line — one for a wallet, one for a drawer (features/reminders.md) */
  function oneCard(entries) {
    var M = root.TesseraManifest;
    var card = el('section', 'wallet-card');
    card.appendChild(el('h3', 'card-heading', 'Letters, waiting.'));
    var list = el('div', 'card-rows');
    entries.forEach(function (e) {
      var row = el('p', 'card-row');
      row.appendChild(el('span', 'mono card-id', e.id));
      row.appendChild(el('span', 'card-when',
        e.openWhenNeeded ? 'when needed' : M.dateInWords(e.openOn)));
      row.appendChild(el('span', 'card-for', 'for ' + (e.to || 'someone')));
      list.appendChild(row);
    });
    card.appendChild(list);
    card.appendChild(el('p', 'card-mark', 'Tessera · a letter keeps its own date. Keep this where you look.'));
    return card;
  }

  function cardSheet(entries) {
    var sheet = el('section', 'sheet sheet-card');
    sheet.appendChild(oneCard(entries));
    sheet.appendChild(el('div', 'card-cut'));
    sheet.appendChild(oneCard(entries));
    return sheet;
  }

  /* the key-escrow card (features/encryption.md): printed at seal time from
     live passphrase/hint values passed in by the caller, never stored in
     the letter folder or manifest. */
  function escrowSheet(o) {
    var sheet = el('section', 'sheet sheet-escrow');
    sheet.appendChild(el('h2', 'sheet-heading', 'A Tessera key card.'));
    if (o.passphrase) {
      sheet.appendChild(el('p', 'escrow-label', 'Passphrase'));
      sheet.appendChild(el('p', 'escrow-value mono', o.passphrase));
    }
    if (o.hint) {
      sheet.appendChild(el('p', 'escrow-label', 'Hint'));
      sheet.appendChild(el('p', 'escrow-value', o.hint));
    }
    sheet.appendChild(el('p', 'sheet-note', 'Give this card to someone who is not the custodian.'));
    sheet.appendChild(el('p', 'sheet-note', 'This unlocks the letter file. A lost passphrase is a lost letter.'));
    sheet.appendChild(footer(o.id, 'key card'));
    return sheet;
  }

  /* show sheets in the print preview overlay; printing prints only #print-root */
  function show(sheets) {
    var overlay = document.getElementById('print-overlay');
    var rootEl = document.getElementById('print-root');
    rootEl.innerHTML = '';
    for (var i = 0; i < sheets.length; i++) rootEl.appendChild(sheets[i]);
    overlay.hidden = false;
    document.body.classList.add('printing-preview');
  }

  function hide() {
    var overlay = document.getElementById('print-overlay');
    overlay.hidden = true;
    document.body.classList.remove('printing-preview');
  }

  function printKit(sealed) { show(kitSheets(sealed)); }
  function printRegister(entries) { show([registerSheet(entries)]); }
  function printCard(entries) { show([cardSheet(entries)]); }
  function printEscrowCard(o) { show([escrowSheet(o)]); }

  var api = { printKit: printKit, printRegister: printRegister, printCard: printCard, printEscrowCard: printEscrowCard, hide: hide, kitSheets: kitSheets };
  root.TesseraPrint = api;
})(typeof self !== 'undefined' ? self : this);
